services:
  mongodb:
    image: mongo:latest
    container_name: keyloom-mongodb
    ports:
      - $MONGODB_PORT:27017
    volumes:
      - ./.volumes/mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD