definitions:
  audience_dtos.CreateAudienceDTO:
    properties:
      description:
        type: string
      display_name:
        type: string
    type: object
  entities.Audience:
    properties:
      created_at:
        type: integer
      description:
        type: string
      display_name:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: integer
    type: object
  entities.User:
    properties:
      created_at:
        type: integer
      email:
        type: string
      id:
        type: string
      password:
        type: string
      updated_at:
        type: integer
    type: object
  token_dtos.AccessTokenResponse:
    properties:
      access_token:
        type: string
      expires_at:
        type: integer
      token_type:
        type: string
    type: object
  user_dtos.CreateUserDTO:
    properties:
      confirm_password:
        type: string
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - confirm_password
    - email
    - password
    type: object
info:
  contact: {}
paths:
  /audiences/:
    post:
      consumes:
      - application/json
      description: Create a new audience with the provided display name and description
      parameters:
      - description: Audience creation data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/audience_dtos.CreateAudienceDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entities.Audience'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create a new audience
      tags:
      - Audiences
  /token/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Dispatch tokens based on the provided grant type
      parameters:
      - description: Grant type
        in: formData
        name: grant_type
        required: true
        type: string
      - description: Username for password grant
        in: formData
        name: username
        type: string
      - description: Password for password grant
        in: formData
        name: password
        type: string
      - description: Client ID for client credentials grant
        in: formData
        name: client_id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/token_dtos.AccessTokenResponse'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Token dispatch endpoint
      tags:
      - Tokens
  /users/:
    post:
      consumes:
      - application/json
      description: Create a new user with the provided email and password
      parameters:
      - description: User creation data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user_dtos.CreateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create a new user
      tags:
      - Users
swagger: "2.0"
